use std::path::{Path, PathBuf};

use devenv_core::{CoreError, CoreResult, ShimSpec, ShimWriter};

#[derive(Debug, Clone)]
pub struct FileShimWriter {
    shim_dir: PathBuf,
    dispatch_command: String,
}

impl FileShimWriter {
    pub fn new(shim_dir: impl Into<PathBuf>) -> Self {
        Self {
            shim_dir: shim_dir.into(),
            dispatch_command: "devenv".to_owned(),
        }
    }

    pub fn with_dispatch_command(mut self, command: impl Into<String>) -> Self {
        self.dispatch_command = command.into();
        self
    }

    pub fn path_for(&self, spec: &ShimSpec) -> PathBuf {
        self.shim_dir.join(spec.binary_name())
    }
}

impl ShimWriter for FileShimWriter {
    fn shim_dir(&self) -> &Path {
        &self.shim_dir
    }

    fn write_shim(&mut self, spec: &ShimSpec) -> CoreResult<()> {
        std::fs::create_dir_all(&self.shim_dir).map_err(|error| {
            CoreError::message(format!(
                "failed to create shim directory `{}`: {error}",
                self.shim_dir.display()
            ))
        })?;

        let path = self.path_for(spec);
        std::fs::write(&path, self.script_for(spec)).map_err(|error| {
            CoreError::message(format!(
                "failed to write shim `{}`: {error}",
                path.display()
            ))
        })?;
        make_executable(&path)?;

        Ok(())
    }
}

impl FileShimWriter {
    fn script_for(&self, spec: &ShimSpec) -> String {
        format!(
            "#!/bin/sh\n# Generated by DevEnv. Do not edit.\nexec {} shim dispatch {} -- \"$@\"\n",
            quote_posix(&self.dispatch_command),
            quote_posix(spec.binary_name())
        )
    }
}

#[cfg(unix)]
fn make_executable(path: &Path) -> CoreResult<()> {
    use std::os::unix::fs::PermissionsExt;

    let mut permissions = std::fs::metadata(path)
        .map_err(|error| {
            CoreError::message(format!(
                "failed to read shim metadata `{}`: {error}",
                path.display()
            ))
        })?
        .permissions();
    permissions.set_mode(0o755);
    std::fs::set_permissions(path, permissions).map_err(|error| {
        CoreError::message(format!(
            "failed to mark shim executable `{}`: {error}",
            path.display()
        ))
    })
}

#[cfg(not(unix))]
fn make_executable(_path: &Path) -> CoreResult<()> {
    Ok(())
}

fn quote_posix(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}
